### PR TITLE
Bug fixes.

### PR DESCRIPTION
**Pull request by jansedlon**
I fixed your documentation. It took me pretty nice day to find out where the problem is. Also I added function to check if abilities are in list or tuple.

### CODE REVIEW

**Comment by jansedlon** [comment]
I forgot to fix the fix :D Give me a few days.

**Comment by LouisTrezzini** [comment]
Looks perfect, thanks!

**Comment by jansedlon** [comment]
No problem man, I'm working on more improvements like removing roles by
name and other stuffs.

Dne 20. 8. 2017 13:59 napsal uživatel "Louis Trezzini" <
notifications@github.com>:

**Comment by jansedlon** [comment]
There is a very interesting problem. Function user_has in your tests work, howerer user_has decorator doesn't work at all in practice. It throws `AttributeError: 'NoneType' object has no attribute 'split'`

**Pull request merged**
